"""
Group B - Perch QC analysis for the prompt ablation experiment.

Reads the manifest generated by prompt_ablation, runs a Perch prediction on each
clip, groups by (species x prompt_level), and checks whether Perch's top
predictions are close to the target species.

Output: for each prompt tier, the proportion of clips where the target species
appears in top1/top5, and the average logit.
"""

import os
import numpy as np
import pandas as pd
import librosa
from perch_hoplite.zoo import model_configs

SYNTH_DIR = r"D:\bird\synth_prompt_test"
MANIFEST  = os.path.join(SYNTH_DIR, "manifest.csv")
PERCH_SR  = 32000
SEG_SEC   = 5

# Scientific names of the target species (corresponding to the file name prefix)
SPECIES_SCI = {
    "Crax_fasciolata":     "Crax fasciolata",
    "Ortalis_canicollis":  "Ortalis canicollis",
}

# =====================================================
# Load Perch + class names
# =====================================================

print("Loading Perch v2 ...")
model = model_configs.load_model_by_name("perch_v2")
dummy = np.zeros(SEG_SEC * PERCH_SR, dtype=np.float32)
out = model.embed(dummy)
LABELSET = list(out.logits.keys())[0]
n_classes = np.asarray(out.logits[LABELSET]).shape[-1]

# Reuse perch_qc's class-name lookup logic (simplified: directly find kagglehub's labels.csv)
import glob
home = os.path.expanduser("~")
perch_classes = None
for f in glob.glob(os.path.join(home, ".cache", "kagglehub", "**", "labels.csv"),
                   recursive=True):
    df = pd.read_csv(f)
    col = "label" if "label" in df.columns else df.columns[0]
    lst = df[col].astype(str).tolist()
    if len(lst) == n_classes:
        perch_classes = lst
        break
assert perch_classes is not None, "No matching class-name table found"
cls_index = {c: i for i, c in enumerate(perch_classes)}

# Index of the target species in the Perch class table (Perch uses iNaturalist
# scientific names, may need fuzzy matching)
def find_class_idx(sci):
    # exact
    if sci in cls_index:
        return cls_index[sci]
    # fuzzy: ignore case, look for containment
    low = sci.lower()
    for c, i in cls_index.items():
        if c.lower() == low:
            return i
    for c, i in cls_index.items():
        if low in c.lower():
            return i
    return None

target_idx = {sp: find_class_idx(sci) for sp, sci in SPECIES_SCI.items()}
print("Target species indices in Perch:", target_idx)

# =====================================================
# Predict clip by clip
# =====================================================

def predict(path):
    y, _ = librosa.load(path, sr=PERCH_SR, mono=True)
    seg_len = SEG_SEC * PERCH_SR
    logits = []
    for s in range(0, max(1, len(y)), seg_len):
        chunk = y[s:s+seg_len]
        if len(chunk) < seg_len:
            chunk = np.pad(chunk, (0, seg_len - len(chunk)))
        o = model.embed(chunk.astype(np.float32))
        logits.append(np.asarray(o.logits[LABELSET]).reshape(-1))
    return np.mean(logits, axis=0)

man = pd.read_csv(MANIFEST)
rows = []
for _, r in man.iterrows():
    path = os.path.join(SYNTH_DIR, r["file"])
    if not os.path.exists(path):
        continue
    ml = predict(path)
    top5 = set(np.argsort(ml)[::-1][:5].tolist())
    top1 = int(np.argmax(ml))
    tgt = target_idx[r["species"]]
    rows.append({
        "species": r["species"],
        "level": r["prompt_level"],
        "target_in_top1": (tgt == top1) if tgt is not None else False,
        "target_in_top5": (tgt in top5) if tgt is not None else False,
        "target_logit": ml[tgt] if tgt is not None else np.nan,
        "top1_pred": perch_classes[top1],
    })

res = pd.DataFrame(rows)

# =====================================================
# Summary: by species x prompt tier
# =====================================================

print("\n" + "=" * 60)
print("Three-tier prompt comparison results")
print("=" * 60)

summary = res.groupby(["species", "level"]).agg(
    n=("target_in_top5", "size"),
    top1_hit=("target_in_top1", "mean"),
    top5_hit=("target_in_top5", "mean"),
    mean_target_logit=("target_logit", "mean"),
).reset_index()
print(summary.to_string(index=False))

print("\nWhat each clip's top1 was actually recognized as:")
print(res[["species", "level", "top1_pred", "target_in_top5"]].to_string(index=False))

print("\nInterpretation:")
print("  - If top5_hit is close to 0 for all three tiers -> prompt engineering can't help, the generated audio is never the target species.")
print("  - If the acoustic/species tiers' hit rate is clearly higher than generic -> prompt engineering is effective and worth using.")
res.to_csv(os.path.join(SYNTH_DIR, "prompt_ablation_perch.csv"), index=False)
print(f"\nDetails saved to prompt_ablation_perch.csv")